name: kazakh_cefr_env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pandas
  - numpy
  - scikit-learn
  - tqdm
  - sentencepiece
  - pip:
      - transformers==4.43.3
      - datasets
      - gradio
      - awesome-align
      - simalign
      - python-dotenv
      - pymorphy2
      - pymorphy3
